const state = { rows: [], analysis: null, page: 0, pageSize: 50, selectedRQ: "RQ01", activeJob: null };
const number = new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 2 });
const byId = (id) => document.getElementById(id);
const numeric = (value) => value === "" || value == null ? null : Number(value);
const median = (values) => { const v = values.filter(Number.isFinite).sort((a,b)=>a-b); if (!v.length) return null; const m = Math.floor(v.length/2); return v.length % 2 ? v[m] : (v[m-1]+v[m])/2; };
const fmt = (value, suffix="") => value == null || Number.isNaN(value) ? "n/a" : `${number.format(value)}${suffix}`;
const percent = (value) => value == null ? "n/a" : `${number.format(value * 100)}%`;
const language = (row) => row.primary_language || "Sem linguagem detectada";

async function request(url, options = {}) { const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Falha na operacao."); return data; }
function metric(label, value, caption) { return `<article class="metric"><span class="metric-label">${label}</span><strong class="metric-value">${value}</strong><span class="metric-caption">${caption}</span></article>`; }
function rqMetric(rows, field) { return median(rows.map((row) => numeric(row[field]))); }

function renderOverview() {
  const rows = state.rows; const ratioRows = rows.filter((r) => numeric(r.closed_issues_ratio) != null);
  byId("summary-cards").innerHTML = [metric("REPOSITORIOS", fmt(rows.length), "CSV carregado"), metric("REPOSITORIOS UNICOS", fmt(new Set(rows.map((r)=>r.name_with_owner)).size), "sem duplicidade"), metric("MEDIANA PRS", fmt(rqMetric(rows,"merged_pull_requests")), "RQ02"), metric("MEDIANA ISSUES FECHADAS", percent(median(ratioRows.map((r)=>numeric(r.closed_issues_ratio)))), "RQ06")].join("");
  const rqs = [["RQ01","Idade do repositorio", `${fmt(rqMetric(rows,"age_days"))} dias`],["RQ02","PRs aceitas",fmt(rqMetric(rows,"merged_pull_requests"))],["RQ03","Releases",fmt(rqMetric(rows,"releases_count"))],["RQ04","Dias desde atualizacao",fmt(rqMetric(rows,"days_since_update"))],["RQ05","Sem linguagem detectada",fmt(rows.filter((r)=>!r.primary_language).length)],["RQ06","Issues fechadas",percent(median(ratioRows.map((r)=>numeric(r.closed_issues_ratio))))],["RQ07","Comparacao por linguagem","ver aba Linguagens"]];
  byId("rq-summary").innerHTML = rqs.map(([rq,label,value])=>`<article class="rq-item"><b>${rq}</b><strong>${label}</strong><span>${value}</span></article>`).join("");
}

function renderLanguages() {
  const grouped = new Map(); state.rows.forEach((row)=>{ const key=language(row); if (!grouped.has(key)) grouped.set(key,[]); grouped.get(key).push(row); });
  const entries = [...grouped.entries()].map(([name, rows])=>({name, rows, prs:rqMetric(rows,"merged_pull_requests"), releases:rqMetric(rows,"releases_count"), update:rqMetric(rows,"days_since_update")})).sort((a,b)=>b.rows.length-a.rows.length);
  byId("language-table").innerHTML = entries.map((item)=>`<tr><td>${item.name}</td><td>${fmt(item.rows.length)}</td><td>${fmt(item.prs)}</td><td>${fmt(item.releases)}</td><td>${fmt(item.update)} dias</td></tr>`).join("");
  byId("language-filter").innerHTML = `<option>Todas</option>${entries.map((item)=>`<option>${item.name}</option>`).join("")}`;
}

function filteredRepositories() { const term=byId("repository-search").value.trim().toLowerCase(); const selected=byId("language-filter").value; return state.rows.filter((row)=>(!term||row.name_with_owner.toLowerCase().includes(term))&&(selected==="Todas"||language(row)===selected)); }
function renderRepositories() { const rows=filteredRepositories(); const pages=Math.max(1,Math.ceil(rows.length/state.pageSize)); state.page=Math.max(0,Math.min(state.page,pages-1)); const shown=rows.slice(state.page*state.pageSize,(state.page+1)*state.pageSize); byId("repository-table").innerHTML=shown.map((r)=>`<tr><td>${r.repository_rank}</td><td>${r.name_with_owner}</td><td>${language(r)}</td><td>${fmt(numeric(r.age_days))} dias</td><td>${fmt(numeric(r.merged_pull_requests))}</td><td>${fmt(numeric(r.releases_count))}</td><td>${fmt(numeric(r.days_since_update))} dias</td><td>${percent(numeric(r.closed_issues_ratio))}</td></tr>`).join(""); byId("page-label").textContent=`Pagina ${state.page+1}/${pages} - ${rows.length} repositorios`; }

function renderSprint3() { const analysis=state.analysis; if (!analysis) { byId("sprint3-cards").innerHTML=""; byId("sprint3-results").innerHTML=""; byId("reading-text").textContent="Gere a analise S03 para ver os resultados."; byId("chart-image").removeAttribute("src"); return; } const results=analysis.results; byId("sprint3-cards").innerHTML=[metric("RQ01 - MEDIANA DE IDADE",fmt(results.RQ01.median_years," anos"),"idade dos repositorios"),metric("RQ02 - MEDIANA DE PRS",fmt(results.RQ02.statistics.median),"pull requests aceitas"),metric("RQ06 - MEDIANA DE ISSUES FECHADAS",fmt(results.RQ06.median_percent,"%"),"957 repositorios com razao valida")].join(""); byId("sprint3-results").innerHTML=["RQ01","RQ02","RQ06"].map((rq)=>{const r=results[rq]; const med=rq==="RQ01"?fmt(r.median_years," anos"):rq==="RQ06"?fmt(r.median_percent,"%"):fmt(r.statistics.median); return `<button class="result-row ${rq===state.selectedRQ?"is-active":""}" data-rq="${rq}"><strong>${rq}</strong><span>${r.metric}</span><span>Mediana: ${med}</span><span>${r.outliers.count} outliers</span></button>`}).join(""); document.querySelectorAll(".result-row").forEach((el)=>el.addEventListener("click",()=>{state.selectedRQ=el.dataset.rq; renderSprint3();})); const r=results[state.selectedRQ]; byId("reading-rq").textContent=state.selectedRQ; byId("reading-title").textContent=r.title; byId("reading-text").textContent=`${r.conclusion}${state.selectedRQ==="RQ06"?` Excluidos: ${r.excluded_no_issues} repositorios sem issues.`:""}`; renderChart(); }
function renderChart() { if (!state.analysis) return; const rq=byId("chart-selector").value; const names={RQ01:"rq01_idade.png",RQ02:"rq02_prs_aceitas.png",RQ06:"rq06_issues_fechadas.png"}; byId("chart-image").src=`/api/chart/${names[rq]}?v=${Date.now()}`; }

function setView(view) { document.querySelectorAll(".view").forEach((node)=>node.classList.toggle("is-visible",node.id===`${view}-view`)); document.querySelectorAll(".nav-item").forEach((node)=>node.classList.toggle("is-active",node.dataset.view===view)); byId("view-title").textContent=document.querySelector(`.nav-item[data-view="${view}"]`).textContent; }
function renderLog(jobs) { const entries=Object.entries(jobs||{}); const running=entries.find(([,job])=>job.running); state.activeJob=running?.[0]||null; const selected=running||entries.at(-1); byId("job-log").textContent=selected?selected[1].lines.join("\n"):"Nenhum processo executado nesta sessao."; }

async function loadData() { const [data,status]=await Promise.all([request("/api/data"),request("/api/status")]); state.rows=data.rows; state.analysis=data.analysis; renderOverview(); renderLanguages(); renderRepositories(); renderSprint3(); renderLog(status.jobs); byId("sidebar-status").textContent=status.csv_exists?`${state.rows.length} repositorios carregados.`:"Nenhum CSV carregado."; byId("app-status").textContent=state.activeJob?"Processo em andamento":"Dados locais prontos"; }
async function startAction(path, payload={}) { try { const result=await request(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}); byId("app-status").textContent=result.message; await loadData(); } catch(error) { alert(error.message); } }
async function poll() { try { await loadData(); } catch(error) { byId("app-status").textContent="Servidor indisponivel"; } finally { window.setTimeout(poll,2500); } }

document.querySelectorAll(".nav-item").forEach((button)=>button.addEventListener("click",()=>setView(button.dataset.view))); byId("refresh-button").addEventListener("click",loadData); byId("collect-button").addEventListener("click",()=>startAction("/api/collect")); byId("analyze-button").addEventListener("click",()=>startAction("/api/analyze")); byId("clear-button").addEventListener("click",()=>{ if(confirm("Remover o CSV local e as analises geradas?")) startAction("/api/clear"); }); byId("chart-selector").addEventListener("change",renderChart); byId("repository-search").addEventListener("input",()=>{state.page=0;renderRepositories();}); byId("language-filter").addEventListener("change",()=>{state.page=0;renderRepositories();}); byId("previous-page").addEventListener("click",()=>{state.page--;renderRepositories();}); byId("next-page").addEventListener("click",()=>{state.page++;renderRepositories();}); byId("snapshot-form").addEventListener("submit",(event)=>{event.preventDefault(); startAction("/api/snapshot",Object.fromEntries(new FormData(event.target)));});
loadData(); poll();
